name: Parents CI/CD - PHP 8.2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Machine To Run On
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Get Composer Cache Directory 2
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        id: actions-cache
        with:
          path: '${{ steps.composer-cache.outputs.dir }}'
          key: '${{ runner.os }}-composer-${{ hashFiles(''**/composer.lock'') }}'
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Cache PHP dependencies
        uses: actions/cache@v2
        id: vendor-cache
        with:
          path: vendor
          key: '${{ runner.OS }}-build-${{ hashFiles(''**/composer.lock'') }}'
      - name: Copy .env
        working-directory: ./src/backend
        run: php -r "file_exists('.env') || copy('.env.example', '.env');" # If .env exist, we use that, if otherwise, copy .env.example to .env and use that instead
      - name: Install Dependencies
        working-directory: ./src/backend
        run: composer install
      - name: Generate key
        working-directory: ./src/backend
        run: php artisan key:generate
      - name: Change Directory Permissions
        working-directory: ./src/backend
        run: chmod -R 777 storage bootstrap/cache
      - name: Clear Config
        working-directory: ./src/backend
        run: php artisan config:clear
      - name: Run coding standard checker
        working-directory: ./src/backend
        run: vendor/bin/pint --test
      - name: Execute tests
        working-directory: ./src/backend
        run: vendor/bin/phpunit
